### ISSUE TITLE
Add es_query_filter as outlier field (especially useful for sigma hits)

### ISSUE THREAD

**Issue by daanraman** [NVISO-BE/ee-outliers#24]
@michielmeersmans FYI

**Comment by maximilienroberti** [comment]
Regarding to [this](https://github.com/NVISO-BE/ee-outliers/blob/022525dc5bd074de059d52781cc49ee47d0a074d/app/helpers/analyzer.py#L135), it seems that this issue is resolved.
es_query_filter is added to the `outliers.elasticsearch_filter` field.
