### ISSUE TITLE
Add Elasticsearch highlighting for Simplequery models

### ISSUE THREAD

**Issue by michielmeersmans** [NVISO-BE/ee-outliers#412]
Elasticsearch has a highlighting feature which returns the field & string that was matched.
This could be used to implement an outliers.matched_field and outliers.matched_value tag.

https://www.elastic.co/guide/en/elasticsearch//reference/current/search-request-body.html#request-body-search-highlighting

**Comment by maximilienroberti** [comment]
Resolved in #517 and #534
