### ISSUE TITLE
Make WARNING into DEBUG as it overloads log output

### ISSUE THREAD

**Issue by daanraman** [NVISO-BE/ee-outliers#444]
`2020-01-27 17:46:02 - WARNING - Outlier 'simplequery_ps_script_block_logging_new_format_autogenerated'  haven't been found in configuration, could not check whitelist
`

**Comment by michielmeersmans** [comment]
Fixed in https://github.com/NVISO-BE/ee-outliers/commit/3e9ebfa74d0dea29708ec580fdd68a1b93813bf7#diff-9bbaf051a6e799094dc386def0c33ac5
