### ISSUE TITLE
Add The Ability to Load Whitelist Terms from a File 

### ISSUE THREAD

**Issue by Bent-Ice** [NVISO-BE/ee-outliers#456]
Adding the ability to specify a file where each line is a term to be whitelisted would make whitelisting much easier and allow for adding an actual list of terms. Ideally the implementation would support per-model whitelists as well as literals and regexps.

**Comment by daanraman** [comment]
Hi there - thanks for reporting. There is currently already an option to add use-case-specific whitelist information (on top of the global whitelist). In addition, the latest version now also supports adding multiple use cases through the --use-cases parameter (will be documented better), so you can specific 1 file per use case.

Example of the "use case specific whitelist" you can add now:

```
...
outlier_type=suspicious connection
outlier_reason=beaconing DNS connection
outlier_summary=beaconing DNS connection to {BroFilter.query}

whitelist_regexps_msft_connect=^beaconing .* connection to .*\.msftconnecttest\.com$
whitelist_literals_outlook = beaconing DNS connection to outlook.office.com
...
```

Does this already help you?
