### ISSUE TITLE
Elasticsearch Authentication

### ISSUE THREAD

**Issue by rhysxevans** [NVISO-BE/ee-outliers#459]
Hi,

I am looking through the documentation and I can't see anywhere to specify a username/password for the connection to elasticsearch. 

Am I missing something ? 

Also is there a limitation on the versions of elasticsearch that are supported ? (Currently running 7.4.0)

Apologies for the newbie questions , any help is appreciated

Thanks

**Comment by daanraman** [comment]
Dear,

Thanks a lot for raising the issue - this is indeed not supported at the moment (we run ee-outliers behind an authenticated proxy). However I will implement this support in the next version. You can follow progress on this ticket!

**Comment by daanraman** [comment]
Around Elasticsearch 7 - we are now testing support for Elasticsearch 7- if you run into issues yourself using it in your ES version, please make sure to create issues so I can track them too!

**Comment by rhysxevans** [comment]
Thank you
