### ISSUE TITLE
Complete documentation for the use of --use-cases parameter

### ISSUE THREAD

**Issue by daanraman** [NVISO-BE/ee-outliers#476]
Was recently added in outliers and I'm not sure that this is properly documented.
@michielmeersmans  could provide input too, who developed this.

**Comment by maximilienroberti** [comment]
Resolved in #500. The documentation for the use of --use-cases parameter can be found [here](https://github.com/NVISO-BE/ee-outliers/blob/master/documentation/GETTING_STARTED.md#step-3-define-docker-container--ee-outliers-parameters-in-the-compose-file).
