### ISSUE TITLE
Unfortunately frozen indices halt outlier detection

### ISSUE THREAD

**Issue by rdepril** [NVISO-BE/ee-outliers#515]
# Context

If a document is read in and tagged as an outlier, but the index becomes read-only before the document can be updated, a `BulkIndexError` gets thrown.

Snippet from the details of such an error: `{'type': 'cluster_block_exception', 'reason': 'index [logstash-eagleeye-wevtfilter-000019] blocked by: [FORBIDDEN/8/index write (api)`

# Problem

It seems like outliers keeps retrying to commit this illegal bulk action, in the mean time no new outliers get detected.

# Solution

Skip frozen indices when writing back?

**Comment by rdepril** [comment]
This issue can be prevented by having an ILM policy that doesn't freeze indices inside the window set by the `history_window_days` parameter

**Comment by michielmeersmans** [comment]
I would indeed skip frozen indices when writing back for now and add a warning log entry

**Comment by maximilienroberti** [comment]
Issue resolved on PR #550
