### ISSUE TITLE
helpers/utils.ps -> flatten_dict

### ISSUE THREAD

**Issue by Mister7F** [NVISO-BE/ee-outliers#60]
If the a key contains the separator character, it can cause an issue

Example:
```
flatten_dict({'i.': {'j':0}}) == flatten_dict({'i': {'.j':0}})
# True
```
Solution:
```
def flatten_dict(d, parent_key='', sep='.'):
    items = []
    for k, v in d.items():
        k = k.replace('\\', '\\\\')
        k = k.replace(sep, '\\.')
        new_key = parent_key + sep + k if parent_key else k
        if isinstance(v, collections.MutableMapping):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)
```

**Comment by daanraman** [comment]
Thanks! I don't think we use this anymore - the only reference I found was in terms.py, in the brute force method - but I don't see why its used. Do you use it @Mister7F ? If not, I will remove it.

**Comment by daanraman** [comment]
Looking at your example again: it's actually expected behaviour to have both the dictionaries in your example be equal! In both cases, they are squashed together as a single key "i.j". I am closing this, but am adding several unit tests that illustrate how this should behave.
